[[themes]]
name = "Catppuccin-mocha"

[themes.palette]
foreground = "#1bcd92"
black = "#45475a"
red = "#e33d6e"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#cdd6f4"
bright_black = "#585b70"
bright_red = "#f37799"
bright_green = "#89d88b"
bright_yellow = "#ebd391"
bright_blue = "#74a8fc"
bright_magenta = "#f2aede"
bright_cyan = "#6bd7ca"
bright_white = "#d6cfbf"

[themes.component_style]
selection = { bg = "Black", modifiers = ["Bold"] }
block_title = { fg = "Red" }
playback_track = { fg = "Red", modifiers = ["Bold"] }
playback_album = { fg = "Red" }
playback_metadata = { fg = "White" }
playback_progress_bar = { fg = "Red" }
playback_progress_bar_unfilled = { fg = "Black" }
current_playing = { fg = "Red", modifiers = ["Bold"] }
page_desc = { fg = "White", modifiers = ["Bold"] }
table_header = { fg = "White" }
playback_status = { fg = "White", modifiers = ["Bold"] }
playback_artists = { fg = "White", modifiers = ["Bold"] }
playlist_desc = { fg = "#a6adc8" }
border = { fg = "White" }
like = { fg = "Red" }

