"$schema" = 'https://starship.rs/config-schema.json'

format = """

[█](#3d2238)\
[█](#5a2a42)\
[█](#7a364e)\
[ 󰣇 ](bg:#7d2a50 fg:#eff0f1)\
$username\
[](bg:#511d44 fg:#511d44)\
$directory\
[](fg:#511d44 bg:#501c45)\
$git_branch\
$git_status\
[](fg:#501c45 bg:#411840)\
[](fg:#411840 bg:#38163e)\
[ ](fg:#38163e)\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#511d44"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "…/"

[username]
show_always = true
style_user = "bg:#7d2a50 fg:#eff0f1"
style_root = "bg:#7d2a50 fg:#eff0f1"
format = '[ $user ]($style)'

[git_branch]
symbol = ""
style = "bg:#6d264d"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#6d264d)]($style)'

[git_status]
style = "bg:#6d264d"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#6d264d)]($style)'

[character]
success_symbol = "[❯](fg:#1bcd92)"
